### ISSUE TITLE
Add authorization for DELETE /zoops/:id

### ISSUE THREAD

**Issue by dyazdani** [dyazdani/zoop#31]
User can delete an existing Zoop only if they wrote it OR it was sent to them.

**Comment by dyazdani** [comment]
@jvaneyken I actually think there is already the proper auth on this endpoint. Maybe confirm it in Postman and move this to the Done section?

**Comment by paloobi** [comment]
@dyazdani @jvaneyken yes it does look like this is already in the codebase, closing Issue to confirm it's done ✌️
