### ISSUE TITLE
Sort out what happens if you fave the same zoop twice

### ISSUE THREAD

**Issue by dyazdani** [dyazdani/zoop#36]

**Comment by paloobi** [comment]
If you don't have a unique constraint on the DB yet, you can look into adding that

I think you add a constraint to the `Faves` model that is just `@@unique([zoopId, faverId])`

**Comment by dyazdani** [comment]
And then run `npx prisma migrate dev`?

**Comment by paloobi** [comment]
Yes, after any schema update, always run migrate, and then add the migration files to GitHub
